require 'fileutils'

default_platform(:ios)

before_all do
	FileUtils.rm_rf("./UnitTestsReport")
	FileUtils.rm_rf("./CodeCoverageReport")
end

# Settings
project 	= 'CICDDemo.xcodeproj'
scheme 		= 'CICDDemo'
testTarget	= 'CICDDemoTests'
configuration 	= 'Debug'
devices 	= ['iPhone 14']

# Paths
$ignore_file_path = '.xcovignore'

# Start
platform :ios do

  	# Lane configuration
	lane :unit_tests do
		scan(
			project: project,
			scheme: scheme,
			configuration: configuration,
			only_testing: testTarget,
			devices: devices,
			prelaunch_simulator: true,
			clean: true,
			skip_build: true,
            		xcodebuild_formatter: 'xcbeautify --renderer github-actions',
			code_coverage: true,
			output_types: 'junit',
			output_directory: "./fastlane/UnitTestsReport"
        	)

		xcov(
			project: project,
			scheme: scheme,
			output_directory: "./fastlane/CodeCoverageReport"
  		)
	end
end